oasislabs/oasis-rs

.circleci/config.yml, .circleci/docker/Dockerfile, examples/ballot/Cargo.toml, examples/ballot/src/main.rs, examples/messaging/Cargo.toml, examples/messaging/src/main.rs, examples/sealed-auctions/Cargo.toml, examples/sealed-auctions/src/main.rs, examples/sealed-auctions/src/types.rs, mantle-build/src/dispatcher_gen/mod.rs, mantle-build/src/main.rs, mantle-build/src/visitor.rs, mantle-build/tests/ui/no_service_derive.stderr, mantle-test/src/ext.rs
Linked PR: https://github.com/oasislabs/oasis-cli/pull/12
=> Simplify mantle-build activation criteria

bcfs/src/bcfs.rs, bcfs/src/file.rs, bcfs/src/tests.rs
=> Implement write-back cache for bcfs

examples/messaging/src/main.rs, mantle-build/src/dispatcher_gen/mod.rs, mantle/Cargo.toml, mantle/src/backend/wasi.rs, mantle/src/lib.rs
Thanks for the suggestion @ryscheng!
=> Give better errors during non-testing x86 build

.circleci/config.yml, examples/erc20/.cargo/config, examples/erc20/Cargo.toml, examples/erc20/src/main.rs
ERC20 token contract in the new newness infra. Happy paths tests. Unhappiness soon to follow.
=> ERC20 token contract

mantle/src/backend/ext.rs, mantle/src/exe.rs
resolves #130
partially fixes #129
=> Misc improvements

mantle-build/src/dispatcher_gen/mod.rs, mantle-build/src/rpc.rs, mantle-build/src/utils.rs, mantle-build/src/visitor.rs, tests/idl_gen/res/DefaultFnService.json, tests/idl_gen/res/TestService.json, tests/idl_gen/src/bin/default_fn.rs, tests/idl_gen/src/bin/types.rs
resolves #104 
Here you go @naheed
=> Default function

.circleci/config.yml, Cargo.toml, mantle-build/Cargo.toml, mantle-build/src/dispatcher_gen/mod.rs, mantle-build/src/error.rs, mantle-build/src/main.rs, mantle-build/src/plugin.rs, mantle-build/src/rpc.rs, mantle-build/tests/compiletest.rs, mantle-rpc/Cargo.toml, mantle-rpc/src/lib.rs, tests/idl_gen/Cargo.toml, tests/idl_gen/run_tests.sh, tests/idl_gen/src/bin/default_fn.rs, tests/idl_gen/src/bin/types.rs, tests/idl_gen/src/lib.rs
=> Bundle interface with wasm

mantle-build/src/plugin.rs, mantle-build/src/rpc.rs, mantle-build/src/visitor.rs, mantle-rpc/Cargo.toml, mantle-rpc/src/lib.rs, tests/idl_gen/res/TestService.json
This should help debugging when using generated clients.
=> Add name to args in interface definition

.circleci/config.yml
This will be handy once rustup supports custom components.
=> Package mantle-build for rustup

bcfs/src/bcfs.rs, bcfs/src/tests.rs
=> Improvements to BCFS

mantle-build/src/dispatcher_gen.rs
https://github.com/rust-lang/rust/commit/44839802853954ca0eea629bb9d94068966f2960 :(
=> Update mantle-build for latest nightly

examples/ballot/Cargo.toml, examples/ballot/src/main.rs, examples/erc20/Cargo.toml, examples/erc20/src/main.rs, examples/hello-world/Cargo.toml, examples/hello-world/src/main.rs, examples/messaging/Cargo.toml, examples/messaging/src/main.rs, examples/sealed-auctions/Cargo.toml, examples/sealed-auctions/src/main.rs, examples/sealed-auctions/src/types.rs, mantle-build/src/main.rs, mantle-build/src/rpc.rs, mantle-build/src/utils.rs, tests/idl-gen/Cargo.toml, tests/idl-gen/res/TestService.json, tests/idl-gen/src/bin/types.rs
=> Use low constant factor collections

.circleci/config.yml, blockchain-traits/Cargo.toml, blockchain-traits/src/lib.rs, mantle-build/src/plugin.rs, mantle-build/src/rpc.rs, mantle-build/src/visitor/hir.rs, mantle-build/tests/ui/bad_import.stderr, mantle-types/Cargo.toml, mantle-types/src/lib.rs, tests/idl-gen/.cargo/config, tests/xcc-a/.cargo/config, tests/xcc-b/.cargo/config
=> Improve error spans for external types

.circleci/config.yml, oasis-std/Cargo.toml, oasis-std/src/backend/ext.rs, oasis-std/src/backend/mod.rs, oasis-std/src/backend/wasi.rs, oasis-std/src/exe.rs, oasis-test/src/ext.rs
This PR adds the necessary functions to access the additional authenticated data (AAD).
Related PR: https://github.com/oasislabs/oasis-parity/pull/154
=> oasis-std: Add ability to get AAD

bcfs/Cargo.toml, bcfs/src/bcfs.rs, bcfs/src/tests.rs, oasis-std/Cargo.toml, oasis-std/src/backend/wasi.rs, tests/idl-gen/res/NonDefaultFnService.json, tests/idl-gen/res/TestService.json, tests/xcc-a/res/ServiceA.json
I am a 💩 programmer. This repo is 🗑 
This is why we [can't have nice things](https://github.com/oasislabs/oasis-parity/issues/160)
=> bcfs: properly handle fd and open flags

docs/rpc_format.md
=> Add rpc format doc

oasis-std/Cargo.toml, oasis-std/src/lib.rs
initially resolves #191 
I'm working on a proxy service generator for the cli, too.
=> Allow client-less calls

README.md, oasis-std/README.md
It was suggested that we add these
=> Add github badges

oasis-build/Cargo.toml, oasis-build/src/gen/imports.rs, oasis-build/src/main.rs, oasis-rpc/Cargo.toml, oasis-rpc/src/import/mod.rs, oasis-rpc/src/import/resolve.rs, oasis-std/README.md, tests/xcc-a/Cargo.toml, tests/xcc-a/res/ServiceA.json, tests/xcc-b/Cargo.toml
Note that the `xcc` tests still don't work because there's no self-client generator yet. ¯\\_(ツ)_/¯
=> Fix imports and xsc

oasis-std/src/exe.rs
Some simple docs to explain what `Context::default` and `Context::delegated` do. Please provide feedback on how to reword things if you think it's necessary.
=> Add docs for Context

.circleci/config.yml, bcfs/Cargo.toml, bcfs/src/bcfs.rs, bcfs/src/file.rs, bcfs/src/tests.rs, memchain/Cargo.toml, memchain/src/block.rs, memchain/src/lib.rs, memchain/src/output.rs, memchain/src/pending_transaction.rs, oasis-types/Cargo.toml, oasis-types/src/lib.rs
resolves #126 
feels good man
TODO: update oasis-parity wasm dep on bcfs
=> Increase BCFS codecov

oasis-rpc/Cargo.toml, oasis-rpc/src/import/file_importer.rs, oasis-rpc/src/lib.rs, tests/src/tests/mod.rs
```
./target/release/walrus-loader  0.62s user 0.01s system 99% cpu 0.632 total
./target/release/wasmparser-loader  0.00s user 0.00s system 93% cpu 0.006 total
```
=> Use wasmparser for reading oasis-interface
